# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lvm_proc.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(676, 461)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Gnome-Applications-Accessories-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.verticalLayout.addWidget(self.mplwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 676, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/fileopen-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filesave-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionBoxZoom = QtGui.QAction(MainWindow)
        self.actionBoxZoom.setCheckable(True)
        self.actionBoxZoom.setChecked(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Gnome-Zoom-Fit-Best-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBoxZoom.setIcon(icon3)
        self.actionBoxZoom.setObjectName(_fromUtf8("actionBoxZoom"))
        self.actionPan = QtGui.QAction(MainWindow)
        self.actionPan.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Mouse_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPan.setIcon(icon4)
        self.actionPan.setObjectName(_fromUtf8("actionPan"))
        self.actionInterval = QtGui.QAction(MainWindow)
        self.actionInterval.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Pen-marker-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInterval.setIcon(icon5)
        self.actionInterval.setObjectName(_fromUtf8("actionInterval"))
        self.actionCut = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Gnome-Edit-Cut-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon6)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Error-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionShowPos = QtGui.QAction(MainWindow)
        self.actionShowPos.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/altimeter_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowPos.setIcon(icon8)
        self.actionShowPos.setObjectName(_fromUtf8("actionShowPos"))
        self.actionDrawCurve = QtGui.QAction(MainWindow)
        self.actionDrawCurve.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pencil.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDrawCurve.setIcon(icon9)
        self.actionDrawCurve.setObjectName(_fromUtf8("actionDrawCurve"))
        self.actionApplyCurve = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/apply.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionApplyCurve.setIcon(icon10)
        self.actionApplyCurve.setObjectName(_fromUtf8("actionApplyCurve"))
        self.actionClearCurve = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/trash-full.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearCurve.setIcon(icon11)
        self.actionClearCurve.setObjectName(_fromUtf8("actionClearCurve"))
        self.actionDistance = QtGui.QAction(MainWindow)
        self.actionDistance.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/measure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDistance.setIcon(icon12)
        self.actionDistance.setObjectName(_fromUtf8("actionDistance"))
        self.actionLowPassFilter = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/filter_32x32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLowPassFilter.setIcon(icon13)
        self.actionLowPassFilter.setObjectName(_fromUtf8("actionLowPassFilter"))
        self.actionScaleY = QtGui.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Fullscreen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionScaleY.setIcon(icon14)
        self.actionScaleY.setObjectName(_fromUtf8("actionScaleY"))
        self.actionRayA = QtGui.QAction(MainWindow)
        self.actionRayA.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Blue Ball.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRayA.setIcon(icon15)
        self.actionRayA.setObjectName(_fromUtf8("actionRayA"))
        self.actionRayB = QtGui.QAction(MainWindow)
        self.actionRayB.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/Green Ball.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRayB.setIcon(icon16)
        self.actionRayB.setObjectName(_fromUtf8("actionRayB"))
        self.actionExp = QtGui.QAction(MainWindow)
        self.actionExp.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exp.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionExp.setIcon(icon17)
        self.actionExp.setObjectName(_fromUtf8("actionExp"))
        self.actionPolyfit = QtGui.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/polyfit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPolyfit.setIcon(icon18)
        self.actionPolyfit.setObjectName(_fromUtf8("actionPolyfit"))
        self.actionThinout = QtGui.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/thinout.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionThinout.setIcon(icon19)
        self.actionThinout.setObjectName(_fromUtf8("actionThinout"))
        self.actionSave_copy_from_setup = QtGui.QAction(MainWindow)
        self.actionSave_copy_from_setup.setIcon(icon2)
        self.actionSave_copy_from_setup.setObjectName(_fromUtf8("actionSave_copy_from_setup"))
        self.actionZero = QtGui.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/zero.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZero.setIcon(icon20)
        self.actionZero.setObjectName(_fromUtf8("actionZero"))
        self.actionScaleRays = QtGui.QAction(MainWindow)
        self.actionScaleRays.setObjectName(_fromUtf8("actionScaleRays"))
        self.actionExchangeRays = QtGui.QAction(MainWindow)
        self.actionExchangeRays.setObjectName(_fromUtf8("actionExchangeRays"))
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_copy_from_setup)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionBoxZoom)
        self.menuEdit.addAction(self.actionPan)
        self.menuEdit.addAction(self.actionInterval)
        self.menuEdit.addAction(self.actionShowPos)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menu.addAction(self.actionRayA)
        self.menu.addAction(self.actionRayB)
        self.menu.addSeparator()
        self.menu.addAction(self.actionScaleRays)
        self.menu.addAction(self.actionExchangeRays)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBoxZoom)
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionInterval)
        self.toolBar.addAction(self.actionDistance)
        self.toolBar.addAction(self.actionShowPos)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionLowPassFilter)
        self.toolBar.addAction(self.actionThinout)
        self.toolBar.addAction(self.actionZero)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDrawCurve)
        self.toolBar.addAction(self.actionPolyfit)
        self.toolBar.addAction(self.actionApplyCurve)
        self.toolBar.addAction(self.actionClearCurve)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionScaleY)
        self.toolBar.addAction(self.actionExp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRayA)
        self.toolBar.addAction(self.actionRayB)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lvm edit", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu.setTitle(_translate("MainWindow", "Обрабатывать лучи", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "&Open", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Открыть файл", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionSave.setText(_translate("MainWindow", "&Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Сохранить файл", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionBoxZoom.setText(_translate("MainWindow", "BoxZoom", None))
        self.actionBoxZoom.setToolTip(_translate("MainWindow", "Масштабирование изображения", None))
        self.actionBoxZoom.setShortcut(_translate("MainWindow", "Z", None))
        self.actionPan.setText(_translate("MainWindow", "Pan", None))
        self.actionPan.setToolTip(_translate("MainWindow", "Перетаскивание", None))
        self.actionPan.setShortcut(_translate("MainWindow", "P", None))
        self.actionInterval.setText(_translate("MainWindow", "Interval", None))
        self.actionInterval.setToolTip(_translate("MainWindow", "Выделение интервала", None))
        self.actionInterval.setShortcut(_translate("MainWindow", "I", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionCut.setToolTip(_translate("MainWindow", "Вырезать интервал", None))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X", None))
        self.actionExit.setText(_translate("MainWindow", "&Exit", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Выход", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Alt+X", None))
        self.actionShowPos.setText(_translate("MainWindow", "showPos", None))
        self.actionShowPos.setToolTip(_translate("MainWindow", "Показывать координаты", None))
        self.actionDrawCurve.setText(_translate("MainWindow", "DrawCurve", None))
        self.actionDrawCurve.setToolTip(_translate("MainWindow", "Рисование кривой", None))
        self.actionApplyCurve.setText(_translate("MainWindow", "ApplyCurve", None))
        self.actionApplyCurve.setToolTip(_translate("MainWindow", "Применить кривую к лучу", None))
        self.actionClearCurve.setText(_translate("MainWindow", "ClearCurve", None))
        self.actionClearCurve.setToolTip(_translate("MainWindow", "Удалить кривую", None))
        self.actionDistance.setText(_translate("MainWindow", "distance", None))
        self.actionDistance.setToolTip(_translate("MainWindow", "Измерение расстояний", None))
        self.actionDistance.setShortcut(_translate("MainWindow", "D", None))
        self.actionLowPassFilter.setText(_translate("MainWindow", "LowPassFilter", None))
        self.actionLowPassFilter.setToolTip(_translate("MainWindow", "Частотная фильтрация сигнала", None))
        self.actionScaleY.setText(_translate("MainWindow", "scaleY", None))
        self.actionScaleY.setToolTip(_translate("MainWindow", "масштабировать луч на выбранном интервале", None))
        self.actionRayA.setText(_translate("MainWindow", "канал 1", None))
        self.actionRayA.setToolTip(_translate("MainWindow", "обрабатывать синюю кривую", None))
        self.actionRayB.setText(_translate("MainWindow", "канал 2", None))
        self.actionRayB.setToolTip(_translate("MainWindow", "обрабатывать зеленую кривую", None))
        self.actionExp.setText(_translate("MainWindow", "exp", None))
        self.actionExp.setToolTip(_translate("MainWindow", "экспоненциальное/линейное стягивание", None))
        self.actionPolyfit.setText(_translate("MainWindow", "polyfit", None))
        self.actionPolyfit.setToolTip(_translate("MainWindow", "Аппроксимация полиномом", None))
        self.actionThinout.setText(_translate("MainWindow", "Проредить", None))
        self.actionThinout.setToolTip(_translate("MainWindow", "проредить точки", None))
        self.actionSave_copy_from_setup.setText(_translate("MainWindow", "Save(copy from setup)", None))
        self.actionSave_copy_from_setup.setToolTip(_translate("MainWindow", "Скопировать описатель и сохранить", None))
        self.actionZero.setText(_translate("MainWindow", "zero", None))
        self.actionZero.setToolTip(_translate("MainWindow", "установка нуля", None))
        self.actionScaleRays.setText(_translate("MainWindow", "scaleRays", None))
        self.actionExchangeRays.setText(_translate("MainWindow", "exchangeRays", None))

from matplotlibwidget import MatplotlibWidget
import res_rc
